---
booktitle: Proceedings of the Impactful and Responsible AI Systems for Education Workshop
shortname: IRAISE
year: '2026'
volume: '339'
start: 2026-06-28
end: 2026-06-28
published: 2026-08-10
conference_number: '3'
sections:
- name: Preface
  title: Preface
- name: Oral
  title: Oral
- name: Poster
  title: Poster
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: IRAISE2026
month: 0
cycles: false
bibtex_editor: Basu Mallick, Debshila and Woodhead, Simon and Wang, Zichao and Ananda,
  Muktha and Burstein, Jill and Murphy, April
editor:
- given: Debshila
  family: Basu Mallick
- given: Simon
  family: Woodhead
- given: Zichao
  family: Wang
- given: Muktha
  family: Ananda
- given: Jill
  family: Burstein
- given: April
  family: Murphy
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Impactful and Responsible AI Systems for Education Workshop
    Held in COEX Convention and Exhibition Center, Seoul, South Korea on 28 June 2026

  Published as Volume 339 by the Proceedings of Machine Learning Research on 10 August 2026.

  Volume Edited by:
    Debshila Basu Mallick
    Simon Woodhead
    Zichao Wang
    Muktha Ananda
    Jill Burstein
    April Murphy

  Series Editors:
    Neil D. Lawrence
    Hoel Kervadec
    Tegan Emerson
date_str: 28 Jun
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v339"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v339
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v339
email: ''
conference:
  name: Impactful and Responsible AI Systems for Education
  url: https://iraise2026.org
  location: COEX Convention and Exhibition Center, Seoul, South Korea
  dates:
  - 2026-06-28
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: v339_clean.bib
# Site settings
# Original source:  v339_clean.bib